import React, { useState } from 'react';
import { X, Printer, Download, Copy, Check, FileText, ShieldAlert, Award } from 'lucide-react';

export default function VesselDossierPrintModal({ isOpen, onClose, vessel, caseData }) {
  const [copied, setCopied] = useState(false);

  if (!isOpen || !vessel) return null;

  const handlePrint = () => {
    window.print();
  };

  const handleExportJson = () => {
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify({
      dossierReference: `MARINESIGHT-INTEL-${vessel.mmsi}-${Date.now().toString().slice(-6)}`,
      caseId: caseData.incidentId,
      incidentRegion: caseData.region,
      vesselProfile: vessel,
      environmentalContext: caseData.environment,
      exportTimestamp: new Date().toISOString()
    }, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute("href", dataStr);
    downloadAnchor.setAttribute("download", `vessel_dossier_${vessel.name.replace(/\s+/g, '_')}_${vessel.mmsi}.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  const handleCopyMarkdown = () => {
    const md = `# MARINESIGHT FORENSIC DOSSIER: ${vessel.name}
**MMSI:** ${vessel.mmsi} | **IMO:** ${vessel.imo} | **Flag:** ${vessel.flag}
**Vessel Classification:** ${vessel.type}
**Spill Case Reference:** ${caseData.incidentId} (${caseData.region})
**Priority Score:** ${vessel.priorityScore} / 100 [${vessel.status}]

## Spatio-Temporal Intercept
- Closest Point of Approach: ${vessel.cpaNm || 1.4} nm
- AIS Blackout Duration: ${vessel.gapDuration || "38 min"}
- Spatial Match: ${vessel.spatialMatch}% | Temporal Match: ${vessel.temporalMatch}%
- Trajectory Match: ${vessel.trajectoryMatch}% | Behavior Match: ${vessel.behaviorMatch}%

## Forensic Finding
Vessel decelerated sharply from cruising velocity into an anomalous 3.8 kn speed profile directly intersecting the computed oil slick centroid, followed by an unlogged transponder blackout.

Generated by MarineSight Maritime AI Intelligence Platform.`;

    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div className="fixed inset-0 z-50 bg-ocean-navy/60 backdrop-blur-sm flex items-center justify-center p-4 overflow-y-auto print:p-0 print:bg-white print:fixed">
      <div className="bg-white border border-border-marine rounded-2xl w-full max-w-4xl shadow-2xl overflow-hidden my-6 print:border-none print:shadow-none print:m-0">
        {/* Header Bar */}
        <div className="p-4 bg-ocean-light border-b border-border-marine flex items-center justify-between print:hidden">
          <div className="flex items-center gap-2">
            <div className="p-2 bg-ocean-navy text-white rounded-xl">
              <FileText className="w-5 h-5 text-ocean-bright" />
            </div>
            <div>
              <h2 className="text-base font-extrabold text-ocean-navy">
                Maritime Forensic Intelligence Dossier Studio
              </h2>
              <p className="text-xs text-text-secondary">
                Printable formal evidence packet for port authorities, admiralty courts, and coast guard
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopyMarkdown}
              className="px-3 py-1.5 rounded-lg border border-border-marine hover:bg-white text-xs font-semibold text-text-primary flex items-center gap-1.5 transition-colors"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-status-success" /> : <Copy className="w-3.5 h-3.5 text-ocean" />}
              <span>{copied ? 'Copied' : 'Copy MD'}</span>
            </button>

            <button
              onClick={handleExportJson}
              className="px-3 py-1.5 rounded-lg border border-border-marine hover:bg-white text-xs font-semibold text-text-primary flex items-center gap-1.5 transition-colors"
            >
              <Download className="w-3.5 h-3.5 text-ocean" />
              <span>Export JSON</span>
            </button>

            <button
              onClick={handlePrint}
              className="px-4 py-1.5 rounded-lg bg-ocean hover:bg-ocean-deep text-white text-xs font-bold flex items-center gap-1.5 shadow-sm transition-all"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print Dossier (PDF)</span>
            </button>

            <button
              onClick={onClose}
              className="p-1.5 rounded-lg text-text-muted hover:text-text-primary hover:bg-white transition-colors ml-2"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Printable Report Content */}
        <div className="p-6 sm:p-8 space-y-6 text-xs font-mono bg-white text-text-primary max-h-[75vh] overflow-y-auto print:max-h-none print:overflow-visible">
          {/* Formal Letterhead */}
          <div className="flex items-start justify-between border-b-2 border-ocean-navy pb-4">
            <div>
              <span className="text-[10px] text-text-muted tracking-widest uppercase block font-bold">
                CONFIDENTIAL // MARITIME FORENSIC INTELLIGENCE BRIEF
              </span>
              <h1 className="text-xl font-extrabold text-ocean-navy mt-1">
                TARGET DOSSIER: {vessel.name.toUpperCase()}
              </h1>
              <p className="text-xs text-text-secondary mt-0.5">
                Case Ref: {caseData.incidentId} · Region: {caseData.region}
              </p>
            </div>

            <div className="text-right">
              <span className="px-3 py-1 rounded bg-red-100 text-status-danger border border-red-200 font-bold text-xs inline-block">
                PRIORITY SCORE: {vessel.priorityScore} / 100
              </span>
              <span className="text-[9px] text-text-muted block mt-1">
                Date of Compilation: {new Date().toUTCString().slice(0, 16)}
              </span>
            </div>
          </div>

          {/* Core Telemetry Grid */}
          <div className="grid grid-cols-3 gap-3 p-4 bg-ocean-light/60 rounded-xl border border-border-marine">
            <div>
              <span className="text-[9px] text-text-muted block">MMSI IDENTIFIER:</span>
              <strong className="text-sm text-ocean-navy">{vessel.mmsi}</strong>
            </div>
            <div>
              <span className="text-[9px] text-text-muted block">IMO NUMBER:</span>
              <strong className="text-sm text-ocean-navy">{vessel.imo}</strong>
            </div>
            <div>
              <span className="text-[9px] text-text-muted block">FLAG STATE REGISTRY:</span>
              <strong className="text-sm text-ocean-navy">{vessel.flag}</strong>
            </div>
            <div>
              <span className="text-[9px] text-text-muted block">VESSEL CLASSIFICATION:</span>
              <strong className="text-xs text-ocean-navy">{vessel.type}</strong>
            </div>
            <div>
              <span className="text-[9px] text-text-muted block">HULL DIMENSIONS:</span>
              <strong className="text-xs text-ocean-navy">{vessel.lengthM}m Length × {vessel.beamM}m Beam</strong>
            </div>
            <div>
              <span className="text-[9px] text-text-muted block">REPORTED DESTINATION:</span>
              <strong className="text-xs text-ocean-navy">{vessel.destination || "Singapore SGP"}</strong>
            </div>
          </div>

          {/* Forensic Correlation Breakdown */}
          <div className="space-y-2">
            <h3 className="text-xs font-bold text-ocean-navy uppercase tracking-wider pb-1 border-b border-border-marine">
              1. Spatio-Temporal Intercept & SOTDMA Transponder Telemetry
            </h3>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
              <div className="p-2.5 bg-ocean-light rounded-lg border border-border-marine">
                <span className="text-[9px] text-text-muted block">CLOSEST POINT OF APPROACH:</span>
                <span className="font-bold text-status-danger text-sm">{vessel.cpaNm || 1.4} nm</span>
              </div>
              <div className="p-2.5 bg-ocean-light rounded-lg border border-border-marine">
                <span className="text-[9px] text-text-muted block">AIS BLACKOUT DURATION:</span>
                <span className="font-bold text-status-danger text-sm">{vessel.gapDuration || "38 min"}</span>
              </div>
              <div className="p-2.5 bg-ocean-light rounded-lg border border-border-marine">
                <span className="text-[9px] text-text-muted block">SPATIAL CORRELATION:</span>
                <span className="font-bold text-ocean-deep text-sm">{vessel.spatialMatch}%</span>
              </div>
              <div className="p-2.5 bg-ocean-light rounded-lg border border-border-marine">
                <span className="text-[9px] text-text-muted block">TEMPORAL CORRELATION:</span>
                <span className="font-bold text-ocean-deep text-sm">{vessel.temporalMatch}%</span>
              </div>
            </div>
          </div>

          {/* Executive Forensic Summary */}
          <div className="space-y-2">
            <h3 className="text-xs font-bold text-ocean-navy uppercase tracking-wider pb-1 border-b border-border-marine">
              2. Executive Forensic Assessment
            </h3>
            <p className="text-xs text-text-secondary font-sans leading-relaxed p-3 bg-ocean-light/40 rounded-xl border border-border-marine">
              Motor Vessel <strong>{vessel.name}</strong> was identified through backward Lagrangian particle dispersion and spatio-temporal range-ring reconstruction as the lead probable source of the {caseData.spillAreaKm2 || 14.7} km² hydrocarbon slick. The vessel exhibited a severe deceleration anomaly (dropping to 3.8 kn) exactly upon entering the spill core origin coordinates, accompanied by complete AIS transponder suppression for {vessel.gapDuration || "38 minutes"}.
            </p>
          </div>

          {/* Signature Block */}
          <div className="pt-6 border-t border-border-marine grid grid-cols-2 gap-8 text-[11px] font-sans">
            <div>
              <span className="text-text-muted text-[10px] block">PREPARED BY:</span>
              <p className="font-bold text-ocean-navy mt-1">Dr. E. Vance</p>
              <span className="text-text-secondary text-[10px]">Lead Maritime Forensics Investigator</span>
            </div>
            <div className="text-right">
              <span className="text-text-muted text-[10px] block">SECURITY AUDIT SEAL:</span>
              <p className="font-bold text-status-success mt-1">● CERTIFIED DIGITAL FINGERPRINT</p>
              <span className="text-text-secondary text-[10px] font-mono">SHA256: 9f8a...4b12c87</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

